### ISSUE TITLE
Sentence Tokenization 

### ISSUE THREAD

**Issue by LBenzahia** [linuxscout/pyarabic#10]
@linuxscout  is there any Sentence Tokenizer function ?

**Comment by linuxscout** [comment]
There is **'tokenize**' in [`araby.py`](https://github.com/linuxscout/pyarabic/blob/master/pyarabic/araby.py)

**Comment by LBenzahia** [comment]
،  @linuxscout   شكرا
،لقد استعملتها لتفريق النص الى كلمات  انا اقصد امكانية التفريق النص الى جمل 
.ان لم تكن موجودة ﻻ عليك 
. وجدت بعض الاعمال لكنهم يحددون نهاية الجملة فقط بـ
هل هذا صحيح دائما اظنه عمل ناقص مارايك انت استاذ ؟
هل بامكانك اعطائي المعايير اللازم اتباعها في تحديد الجمل  حتى اتمكن من انشاء واحد بنفسي؟

**Comment by linuxscout** [comment]
Ok, you mean Chuncking
I have one in mishkal [adaat.py](https://github.com/linuxscout/mishkal/blob/master/core/adaat.py).
It needs morphology and syntactical analysis,

**Comment by LBenzahia** [comment]
Thanks a lot it's helpful.
