### ISSUE TITLE
0.6.3 breaks on Python 3

### ISSUE THREAD

**Issue by tahoar** [linuxscout/pyarabic#14]
I updated to 0.6.3 and my application fails with this Traceback:

Traceback (most recent call last):
  File "C:\Users\tahoar\slatedesktop\share\plugins\ar\tokenizer.py", line 23, in <module>
    from pyarabic import araby
  File "C:\Program Files\Python36\lib\site-packages\pyarabic\araby.py", line 219
    HARAKAT_PATTERN = re.compile(ur"[" + u"".join(HARAKAT) + u"]", re.UNICODE)
                                     ^
SyntaxError: invalid syntax

I have done considerable work on your code to update all modules for Python 2.7 and 3.x compatibility and I'd like to contribute those changed to trunk. Please review this attachment and run through your tests.

Thanks,
Tom

[pyarabic.zip](https://github.com/linuxscout/pyarabic/files/1866066/pyarabic.zip)

**Comment by linuxscout** [comment]
Thanks a lot I update it to be compatible with python 2 and 3,
can you tell me if it works
