### ISSUE TITLE
number_to_text method is missing, isn't it?

### ISSUE THREAD

**Issue by abdelrhmanghreeb** [linuxscout/pyarabic#15]
The documentation mentions that the library has a number to text (21 -> واحد وعشرون) method, but I can't find it. Would you please point to it? And give an example of how to use it?

**Comment by linuxscout** [comment]
Yes, There is this feature, you can view full docs on [http://pythonhosted.org/PyArabic/](http://pythonhosted.org/PyArabic/).
Here you have an example
```python
import pyarabic.number as number
 arn = number.ArNumbers()
arn.int2str("124538")
print arn.int2str("124538").encode('utf8')
مئة و أربع و عشرون ألف و خمسمئة و ثماني و ثلاثون
```

**Comment by abdelrhmanghreeb** [comment]
@linuxscout Thanks for your reply.
One more question that I am not able to get an answer to from the documentation; Can the library convert ordinals as well not only cardinals.
Example:
```
6 => سادس/سادسة
```

**Comment by linuxscout** [comment]
no
