### ISSUE TITLE
Adding support for stop words?

### ISSUE THREAD

**Issue by mohataher** [linuxscout/pyarabic#16]
Great work Taha. Have you considered adding stop words removal support? There's a good list here that you could start with. https://github.com/mohataher/arabic-stop-words

**Comment by linuxscout** [comment]
وعليكم السلام
أعتقد أن الاستبعاد مكانه في مكتبة أخرى،
شكرا على مشروع المستبعدات، 
أقترح عليك أن تلقي نظرة على
https://github.com/linuxscout/arabicstopwords
