### ISSUE TITLE
text2number is not converting 400 , 104 properly

### ISSUE THREAD

**Issue by aravindpadu** [linuxscout/pyarabic#18]
أربعة مئة  = 400   ->  giving output as 104
104 = مائة وأربعة -> giving puput as 100 و               4

**Comment by linuxscout** [comment]
Salam,
There are two functions: 
- text2number(text): which convert  words into integers
- number2text(number): to convert number to words.
I tested the previous given examples:
```python
>>> import pyarabic.number as pyn
>>>pyn.number2text(104)
مئة و أربع
>>> pyn.number2text(400)
أربعمئة
>>> pyn.number2text(104)
مئة و أربع
>>> print pyn.text2number('أربعمئة')
>>> pyn.text2number(u'أربعمئة')
400
>>> pyn.text2number(u'مئة وأربعة')
104
>>> pyn.text2number(u'مائة وأربعة')
104
```
I will check if 'اربعة مئة' is not a correct spelled form.
for 

>  104 = مائة وأربعة -> giving puput as 100 و 4
I doesn't understand the question.
Thanks

**Comment by aravindpadu** [comment]
Hi Taha,
I am actually using google translate for converting english to arabic. 
I translated "one hundred and four" and it gave me مائة واربعة, (i have no idea about correctness of this spelling)
for this input text2number gave 100واربعة as output

**Comment by linuxscout** [comment]
You can use the two function to handle this feature.
I agree that the word "اربعة" is misspelled.
