### ISSUE TITLE
Which open source license is this under?

### ISSUE THREAD

**Issue by Flimm** [linuxscout/pyarabic#20]
`setup.py` mentions that this is licensed under GPL. However, which version of the GPL? And where is the full text of the license?

I recommend including a file named `LICENSE.txt` with the full text of GPLv3. Here are instructions: https://choosealicense.com

**Comment by linuxscout** [comment]
Thanks, It just a miss, I fixed it.

**Comment by Flimm** [comment]
شكرا!
