### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by Flimm** [linuxscout/pyarabic#23]
The README.md file points to this site for documentation:

https://pythonhosted.org/PyArabic/

Unfortunately, it currently is broken. It does not display properly on Chrome or Firefox. If I look in the console, I see these errors:

>     Load denied by X-Frame-Options: https://pythonhosted.org/PyArabic/toc.html does not permit framing.

I'm guessing pythonhosted.org recently turned on the `X-Frame-Options: deny` header, making it impossible to use iframes the way the current documentation uses iframes.

**Comment by linuxscout** [comment]
Salam,
I think That the new pypi site doesn't support documentation, or it changes the way to make document, Have you any idea how can I update it.

**Comment by akkk33** [comment]
@linuxscout Could you please create a project account in [Read the docs](http://readthedocs.io/) ? 
If you don't have time to type documentation, contributors will take care of it.

**Comment by linuxscout** [comment]
Thanks, I uploaded doc on https://pyarabic.readthedocs.io/ar/latest/index.html

**Comment by Flimm** [comment]
Wonderful!
