### ISSUE TITLE
pip installation is missing stack.py

### ISSUE THREAD

**Issue by boussouira** [linuxscout/pyarabic#3]
Hi,

when installing from pip, from pyarabic import araby result in this error:
  File "<stdin>", line 1, in <module> 
  File "/home/naruto/Desktop/herok-app/venv/local/lib/python2.7/site-packages/pyarabic/araby.py", line 28, in <module>
    from stack import *
ImportError: No module named stack                                                                                                                                                                                
the site-packages/pyarabic folder  only contains this files:
araby.py  araby.pyc  __init__.py  __init__.pyc

**Comment by assem-ch** [comment]
Hi, this file should be in the package of pyarabic, but as I checked it's not in the package uploaded to pypi.

I suggest to download the source code from here (github):  https://github.com/linuxscout/pyarabic/archive/master.zip

**Comment by boussouira** [comment]
Yes, downloading it will solve the problem, but my project is on Heroku, pip is the only why to fix this problem in this case.
Hope there will be a new version on pypi

**Comment by assem-ch** [comment]
I will send a pull request with the fix now. @linuxscout will upload it to PyPi so you can use install it directly through pip.

**Comment by boussouira** [comment]
Can't we get ride of Stack class? bult-in List can be used as Stack (LIFO)
https://docs.python.org/2/tutorial/datastructures.html#using-lists-as-stacks

**Comment by boussouira** [comment]
And thank you for your help

**Comment by assem-ch** [comment]
stack.py is just one of missing modules. There are many other modules that are not included on current pypi package: arabrepr.py  kalima.py  named_const.py  named.py  number_const.py  number.py  propernouns.py  stack.py  unshape.py.

However, stack.py is just a wrapper for the use of  built-in list as a stack .

**Comment by boussouira** [comment]
Thank you for the fix, btw is this project still active?

**Comment by assem-ch** [comment]
yes, I think so. You need it urgently?

**Comment by boussouira** [comment]
No, just wondering :)

**Comment by boussouira** [comment]
The import error is fixed in the new version.
however there still and warning/error that appair after intalling from pip (the last line in harf.py):
```
# pip install pyarabic
Collecting pyarabic
  Downloading PyArabic-0.5.1.zip (97kB)
    100% |################################| 98kB 409kB/s 
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'Platform'
      warnings.warn(msg)
Installing collected packages: pyarabic
  Running setup.py install for pyarabic
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'Platform'
      warnings.warn(msg)
    Sorry: IndentationError: expected an indented block (harf.py, line 511)
Successfully installed pyarabic-0.5
```

Thank you @assem-ch and @linuxscout

**Comment by assem-ch** [comment]
@boussouira try the new one 0.5.2

**Comment by boussouira** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Okay fixed :)
    Thank you again
