### ISSUE TITLE
 is_arabicstring

### ISSUE THREAD

**Issue by Marwa-Hashem** [linuxscout/pyarabic#31]
It came with this error:
NameError: name 'is_arabicstring' is not defined
only is_arabicrange is working well

**Comment by linuxscout** [comment]
I just tested it, it works,
```python
>>> import pyarabic.araby as araby
>>> araby.is_arabicstring("taha")
False
>>> araby.is_arabicstring(u"سلام قولا من رب رحيم")
True
>>> araby.is_arabicstring(u"سلام قولا من رب رحيمtaha")
False

```

**Comment by Marwa-Hashem** [comment]
Then is there anyway to get just words not Arabic numbers or punctuation.

**Comment by linuxscout** [comment]
You can use tokenize() function to split text into words, then use is_arabicword() function which return True, if the word is arabic, with no numbers or punctuation.
