### ISSUE TITLE
Normalization of Number words

### ISSUE THREAD

**Issue by mAboshokor** [linuxscout/pyarabic#32]
most of the number words found in Arabic text is usually normalized as Arabic speakers use words like "الف" instead of "ألف" and since the modulo already includes various normalization methods it is saner to use the normalized version of the word instead of the original form

**Comment by linuxscout** [comment]
Thanks for this proposition, but The word "الف" is mistaken, I think we can allow it as a parameter, but not as a correct form, this will lead to extract wrong phrases.
I think, we can add a default parameter to function, which enable normalization for normalized words.

**Comment by mAboshokor** [comment]
Hi Dr. can you please recheck the PR at #33

**Comment by linuxscout** [comment]
I'm reviewing it.
