### ISSUE TITLE
Installing on windows using pip

### ISSUE THREAD

**Issue by WissamAntoun** [linuxscout/pyarabic#34]
I just tried installing using pip, but it gave me encoding error in the setup.py file. 
To fix this i added encoding='utf-8'.
```
def readme():
    with open('README.md',encoding='utf-8') as f:
        return f.read()
```

**Comment by olive9591** [comment]
can you help me through the download step by step? would really appreciate it <3 
thanks

**Comment by olive9591** [comment]
i tried installing it with pip but encountered an error how should i deal with this???

**Comment by WissamAntoun** [comment]
hey,

I went ahead and forked this repository and fixed the issue.
you can clone it here https://github.com/WissamAntoun/pyarabic 
then go to the pyarabic directory,
and `python setup.py install --user`

**Comment by linuxscout** [comment]
I fixed this issue, Thanks
