### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by geohadab** [linuxscout/pyarabic#38]
I am happy to see a documentation website for the library 

I suggest using sphinx-rtd theme which supports RTL languages 

https://sphinx-rtd-theme.readthedocs.io/en/stable/
https://github.com/readthedocs/sphinx_rtd_theme#contributing-or-modifying-the-theme 

thank you

**Comment by linuxscout** [comment]
I will work on.

**Comment by linuxscout** [comment]
Thanks for your recommendation, 
I worked on,
you can see it on:
[https://pyarabic.readthedocs.io](https://pyarabic.readthedocs.io )
