### ISSUE TITLE
New features in Python 2 that could be useful in this codebase

### ISSUE THREAD

**Issue by Flimm** [linuxscout/pyarabic#41]
I thought I would share with you a couple of new Python 3 features that be useful for this codebase. I know that this codebase currently supports Python 2, but [Python 2 is now no longer supported by core developers](https://www.python.org/doc/sunset-python-2/), so this may be the time to drop support for Python 2 and start using these newer features.

This is just a friendly message, I am not expecting you to have the same opinion as me or to prioritise this. Treat this as a conversational message, not as a bug report. Feel free to close this if you intend to keep on supporting Python 2.

# `\N{name}` in Python string literals:

Python 3.3 supports this new feature, see [release notes](https://docs.python.org/3/whatsnew/3.3.html#other-language-changes):

> Added support for Unicode name aliases and named sequences. Both `unicodedata.lookup()` and `'\N{...}'` now resolve name aliases, and `unicodedata.lookup()` resolves named sequences too.

For example:

```python
>>> "\u0649" == "\N{arabic letter alef maksura}"
True
```

We can tidy up the codebase to avoid using the hard to read `\u0649` escape sequences.

# `\N{name}` in Python regexes:

Python 3.8 supports these new features, see [release notes](https://docs.python.org/3/whatsnew/3.8.html#other-language-changes):

> Added support of `\N{name}` escapes in regular expressions:
> 
> ```python
> >>> notice = 'Copyright © 2019'
> >>> copyright_year_pattern = re.compile(r'\N{copyright sign}\s*(\d{4})')
> >>> int(copyright_year_pattern.search(notice).group(1))
> 2019
> ```

This would allow us to improve code like this:

```python
ALEF_MAKSURA = u"\u0649"
m = re.match(r"^(.)*[%s]" % ALEF_MAKSURA, word)
```

to look like this instead:

```python
m = re.match(r"^(.)*[\N{arabic letter alef maksura}]")
```

This is especially useful when using raw strings literals (string literals that are prefixed with `r`), as it is not possible otherwise to use `\N{...}` in a raw string for the intended effect. Raw string literals are often used in regexes.

**Comment by linuxscout** [comment]
Ok, It's a great feature, I will work on it, It reduce ambiguity and improves readability.
