### ISSUE TITLE
Does pyarabic support Python 3.x

### ISSUE THREAD

**Issue by ODosari** [linuxscout/pyarabic#42]
Hi, I am wondering if the package supports python 3.x

**Comment by linuxscout** [comment]
Salam, It does,
https://pypi.org/project/PyArabic/#files

**Comment by meedawi** [comment]
وعليكم السلام ورحمة الله، شكرا أخي على الرد.

‫في الخميس، 4 يونيو 2020 في 6:34 م تمت كتابة ما يلي بواسطة Taha Zerrouki
(طه زروقي ) <‪notifications@github.com‬‏>:‬
