### ISSUE TITLE
Import Error - ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by Hako-Ben** [linuxscout/pyarabic#50]
Salam Dr.Taha, :wave:

There is an ImportError when importing module number.py :confused:

**To reproduce**
``` python 
>>> import pyarabic.number as number 
```

**Error Report**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\venv\lib\site-packages\pyarabic\number.py", line 27, in <module>
    from six import text_type as unicode
ModuleNotFoundError: No module named 'six'
```

**My System Version**
- Python 3.8.6

**Temporary fix**
Installing package six using ```pip install six```

**Suggestions**
I suggest adding **six** "_current version_" into the dependencies of pyarabic within  [install_requires](https://packaging.python.org/discussions/install-requires-vs-requirements/#id5)
I'm relatively new to Python "couples of months" and this suggestion is based on my humble experience with Python. :pleading_face:
This is also my first issue submission into GitHub so please bear with me! :sweat_smile:

**Comment by linuxscout** [comment]
Thanks a lot,
I solved it, It will be available soon.
