### ISSUE TITLE
Issue checking for a valid Arabic word

### ISSUE THREAD

**Issue by ahmedelq** [linuxscout/pyarabic#51]
## Expected Behaviour
`An Arabic word doesn't contain spaces, digits and punctuation`
## Current Behaviour
`araby.is_arabicword('؛')` gives True.

**Comment by linuxscout** [comment]
Thanks for you message, 
I think that this behaviour can be justified, by the way that arabic word can have punctuation at the end, for example ("أأكلت؟"),
We can add more options for this function.
Thanks
