### ISSUE TITLE
initial and middle dotless noon is not working

### ISSUE THREAD

**Issue by mzeidhassan** [linuxscout/pyarabic#53]
As-salamo Alaikom Taha @linuxscout ,

I am testing the removal of dots above or below Arabic letters, and everything seems to be working fine, except for initial and middle noon (حرف النون).

Any idea if there is a fix for this? 

Here is a screen shot.
![image](https://user-images.githubusercontent.com/7589948/118423185-b9ae8680-b6c4-11eb-8a1b-ef6e5d2de533.png)

Thanks

**Comment by linuxscout** [comment]
Salam,
is this feature included in PyArabic?
or you want a help for this case?
Thanks

**Comment by linuxscout** [comment]
من الجيد إضافة هذه الميزة،
وتحضرني بعض الأفكار، يمكن استعمالها كلها معا أو بعض منها:
* استبدال الحروف بما يقابلها من حروف أخرى مشابهة
* استبدالها بحروف غير منقوطة
* استبدالها بحروف فارسية غير مستعملة في العربية بنقط مختلفة
* استعمال حروف العلة الصغيرة مثل الألف الخنجرية والياء الصغيرة والواو الصغيرة المستعملة في المصحف
* تقسيم الكلمات مثل: حم اس، نتن ياهو، فلس طين
* استخدام طريةق المغاربة في كتابة المصحف:
 * حروف نهائية بلا حروف الياء والنون والفاء والقاف لأنها لا تلتبس حتى دون نقاط
 * الفاء المنقوطة من أسفل
*  استخدام بعض التنويعات الأعجمية للحروف مثل الهمزة على الواو والهمزء على الياء، هناك تنويعات كثيرة بالعربية
* ممكن اعتماد طريقة عشوائية في هذه التغييرات

**Comment by linuxscout** [comment]
المشكلة الحقيقية ليست في استبدال الحروف بعضها ببعض، بل بدعم الحروف في الخطوط الحاسوبية
مما قد يسبب مشكلة في العرض

**Comment by linuxscout** [comment]
* وضع قائمة خاصة بالكلمات وتعويضها بكلمات أخرى
* رأيت أحدهم يغير كلمة صهاينة بكلمة صابونيين

**Comment by linuxscout** [comment]
هناك أفكار كثيرة، ممكن الاستفادة منها، بحيث يكون النص مقروءا من البشر، وغير مقروء من
 الآلة، يسمى هذا "اللغويات النفسية"
موقع تجاوز فكرة جيدة
https://tajawz.com/

**Comment by linuxscout** [comment]
https://www.dotless.app/

[People Are Using an Ancient Method of Writing Arabic to Combat AI Censors](https://hyperallergic.com/647086/people-are-using-an-ancient-method-of-writing-arabic-to-combat-ai-censors)

**Comment by khiiraldyn** [comment]
إستعمل نفس الحرف الذي تستعمله للباء عندما تكون النون في بداية ووسط الكلمة واستعمل نون الغنة في نهاية الكلمة

**Comment by khiiraldyn** [comment]
من الأحسن أن لا تجعل لكل حرف منقوط حرفا غير منقوط لأنه سرعان ما ستتترف عليه خوارزميات ذ.إ 
إجعل الحروف المنقوطة تشترك في نفس الحرف المنقوط
وإذا كان هناك أكثر من حرف غير منقوط له نفس الشكل فاجعل البرنامج يبدل بينها عشوائيا

**Comment by mzeidhassan** [comment]
معذرة أخي الفاضل طه @linuxscout لتأخري في الرد.

أتمنى إضافة هذه الميزة لأنها أصبحت مطلوبة وظهرت أهميتها مؤخرًا. 
قمت بعمل كود بسيط يعمل مع كل الأحرف ما عدا حرف النون في اول الكلمة أو في منتصفها. 

انتهز الفرصة وأود أن أشكرك على مجهوداتك الطيبة لخدمة اللغة العربية أخي الفاضل.

**Comment by linuxscout** [comment]
@zibanpirate 
هذاوينجاتفيباليانوتلصقالكلماتكاملمعبعض،
هنا البرنامج تغيبلو ولكن الانسان يقدر يقراها،
على كل حال، الدالة لي راح تخدمها من الاحسن تعطيك الخيارات تع التشفير:
const arText = encode({
oneWordSentense: true,
noDots: true,
similarWords: true,
…etc
})

**Comment by ZibanPirate** [comment]
@linuxscout 
> @ZibanPirate
> هذاوينجاتفيباليانوتلصقالكلماتكاملمعبعض،
> هنا البرنامج تغيبلو ولكن الانسان يقدر يقراها،
> على كل حال، الدالة لي راح تخدمها من الاحسن تعطيك الخيارات تع التشفير:
> const arText = encode({
> oneWordSentense: true,
> noDots: true,
> similarWords: true,
> …etc
> })
 ممكن تضيف مزيد من التخصيص في خاصية التشفير بالصاق الكلمات٫ حيث انك في عوض تحويل النص كامل الى كلمة واحدة٫ ممكن توفر خيار تقسيم الكلمات عند المرور بحرف معين٫ مثلا الفاصلة.

**Comment by linuxscout** [comment]
ربما سنتوسع في الامر ونضع عددا من الدوال،
بدلا من دالة واحدة،
وفيها الكثير من الخيارات،
يعني نحولها إلى مكتبة خاصة

الفكرة أن التشويش يعني أنها لا يمكن أن تكون عكسية،

في الوقت نفسه، يمكن التفكير في برامج ذكية لفك هذ=ا الغموض وحل مشكلة التشويش

**Comment by khiiraldyn** [comment]
https://www.facebook.com/100022916238301/posts/982069772566888/?app=fbl
