### ISSUE TITLE
normalize_searchtext import errors + typo's

### ISSUE THREAD

**Issue by e-lobo** [linuxscout/pyarabic#54]
from pyarabic.normalize import normalize_searchtext
normalize_searchtext("بحث")
throws 
1. import errors

![image](https://user-images.githubusercontent.com/41537985/124346655-1b816c00-dbf1-11eb-9a69-0e0b98307476.png)

 2. throws typo errors
 
![image](https://user-images.githubusercontent.com/41537985/124346568-a877f580-dbf0-11eb-8384-ac47ffc2a183.png)

**Comment by linuxscout** [comment]
Thank you for your message,
I fixed it, and I upload a new version library on PiPy
Thanks
