### ISSUE TITLE
prefix and suffix

### ISSUE THREAD

**Issue by Rawabi20** [linuxscout/pyarabic#75]
Hi
is there any function that could provide prefix and suffix tokenization?
such as:
المدخل: ولن نبالغ إذا قلنا: إن 'هاتف' أو 'كمبيوتر المكتب' في زمننا هذا ضروري
المخرج: و+ لن نبالغ إذا قل +نا : إن ' هاتف ' أو ' كمبيوتر ال+ مكتب ' في زمن +نا هذا ضروري

**Comment by linuxscout** [comment]
وعليكم السلام
يمكنك استعمال مكتبة تاشفين للتجذيع الخفيف، تقدم تقسيم الزوائد دون قاموس،
https://github.com/linuxscout/tashaphyne
أو مكتبة القلصادي، تعطي تحليلا أعمق، مع القاموس
https://github.com/linuxscout/qalsadi
مع تحياتي
